# Generated by Django 5.0.14 on 2026-08-06 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('research', '0003_researchquery_is_latest_researchquery_parent_query_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='research.researchquery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_rating',
            },
        ),
    ]
