# Generated by Django 5.0.14 on 2026-08-06 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_add_report_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrating',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
